### ISSUE TITLE
Move the Prometheus blog post to the new documentation page

### ISSUE THREAD

**Issue by korvoj** [nmaas-platform/nmaas-docs#28]
As discussed during the last VC, https://wiki.geant.org/pages/viewpage.action?pageId=267255809 is a short documentation page which can be converted to Markdown and moved to https://docs.nmaas.eu.

Previously moved blog posts can be used as reference:
- https://github.com/nmaas-platform/nmaas-docs/tree/master/docs/blog
- https://raw.githubusercontent.com/nmaas-platform/nmaas-docs/master/docs/blog/blog2/nmaas-101-2.md

More detailed instructions are available on https://wiki.geant.org/display/gn43wp6/NMaaS+Documentation+Migration.

**Comment by llopat** [comment]
@korvoj was this issue completed by someone already?

**Comment by korvoj** [comment]
@llopat , no, the page is still missing from docs.nmaas.eu. It should be under the `Blog` section - https://docs.nmaas.eu/blog/blog3/nmaas-101-3/

**Comment by llopat** [comment]
@kbeyro please pick this up when you have some time
