### ISSUE TITLE
Move the Domain Admin Guide

### ISSUE THREAD

**Issue by korvoj** [nmaas-platform/nmaas-docs#48]
Source: [NMaaS Domain Admin Guide](https://wiki.geant.org/display/NMAAS/NMaaS+Domain+Admin+Guide)

**Comment by korvoj** [comment]
@llopat, please add a Warning section as the one shown in the picture below on https://wiki.geant.org/display/NMAAS/NMaaS+Domain+Admin+Guide. It seems that I do not have the necessary permissions to edit this page.

![image](https://github.com/nmaas-platform/nmaas-docs/assets/4062681/b3dddc86-f554-421a-b35c-fdfa3a9cbab0)

(The above notice is posted on https://wiki.geant.org/display/NMAAS/NMaaS+Application+Manager+Guide).

The new URL for the Domain Admin Guide is: https://docs.nmaas.eu/guides/domain-admin-guide/

**Comment by llopat** [comment]
> @llopat, please add a Warning section as the one shown in the picture below on https://wiki.geant.org/display/NMAAS/NMaaS+Domain+Admin+Guide. It seems that I do not have the necessary permissions to edit this page.
> 
> ![image](https://user-images.githubusercontent.com/4062681/263943551-b3dddc86-f554-421a-b35c-fdfa3a9cbab0.png)
> 
> (The above notice is posted on https://wiki.geant.org/display/NMAAS/NMaaS+Application+Manager+Guide).
> 
> The new URL for the Domain Admin Guide is: https://docs.nmaas.eu/guides/domain-admin-guide/

Notice added to the old wiki page
